language: node_js

node_js:
    - node # will use latest node

before_script: # commands to run before the build step
    - npm install -g --silent firebase-tools
    - npm install -g --silent @angular/cli

script: # the build step
    - ng build --prod

branches:
    only:
        - master

deploy:
    provider: firebase
    token:
        secure: $FIREBASE_TOKEN
    project: $FIREBASE_PROJECT

notifications:
    email: # only receive email when the build status changes (someone broke the build!)
        on_failure: elwindwalker@gmail.com
        on_success: mdepietro@fragua.com.ar
